# Generated by Django 3.0.7 on 2020-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_auto_20200611_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='route',
        ),
    ]
