# Generated by Django 3.0.7 on 2020-06-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('trackerapp', '0004_remove_entry_route'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Place',
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='location',
            new_name='place',
        ),
    ]
